apiVersion: apps/v1
kind: Deployment
metadata:
  name: flask-app
spec:
  selector:
    matchLabels:
      run: flask-app
  replicas: 1
  template:
    metadata:
      labels:
        run: flask-app
    spec:
      containers:
      - name: flask-app
        image: gcr.io/ermias-biz/capstone-project-cluster-prod-flask-app:latest
        ports:
        - containerPort: 8000
        command: ["gunicorn"]
        args: ["-w", "4", "-b", "0.0.0.0:8000", "wsgi:app"]
        imagePullPolicy: Always
#        resources:
#          requests:
#            cpu: '2'
#            memory: '8Gi'
        env:
        - name: DB_USER
          valueFrom:
            secretKeyRef:
              name: database-info
              key: username
        - name: DB_PASS
          valueFrom:
            secretKeyRef:
              name: database-info
              key: password
        - name: DB_NAME
          valueFrom:
            secretKeyRef:
              name: database-info
              key: database
      - name: cloud-sql-proxy
        # It is recommended to use the latest version of the Cloud SQL proxy
        # Make sure to update on a regular schedule!
        image: gcr.io/cloudsql-docker/gce-proxy:latest
        command:
          - "/cloud_sql_proxy"

          # If connecting from a VPC-native GKE cluster, you can use the
          # following flag to have the proxy connect over private IP
          # - "-ip_address_types=PRIVATE"

          # Replace DB_PORT with the port the proxy should listen on
          # Defaults: MySQL: 3306, Postgres: 5432, SQLServer: 1433
          - "-instances=ermias-biz:us-central1:capstone-data=tcp:5432"

          # This flag specifies where the service account key can be found
          - "-credential_file=/secrets/service_account.json"
        securityContext:
          # The default Cloud SQL proxy image runs as the
          # "nonroot" user and group (uid: 65532) by default.
          runAsNonRoot: true
        volumeMounts:
          - name: gen-capstone-svc-acct-volume
            mountPath: /secrets/
            readOnly: true
        # Resource configuration depends on an application's requirements. You
        # should adjust the following values based on what your application
        # needs. For details, see https://kubernetes.io/docs/concepts/configuration/manage-resources-containers/
#        resources:
#          requests:
#            # The proxy's memory use scales linearly with the number of active
#            # connections. Fewer open connections will use less memory. Adjust
#            # this value based on your application's requirements.
#            memory: "2Gi"
#            # The proxy's CPU use scales linearly with the amount of IO between
#            # the database and the application. Adjust this value based on your
#            # application's requirements.
#            cpu: "1"
      volumes:
        - name: gen-capstone-svc-acct-volume
          secret:
            secretName: gen-capstone-svc-acct