apiVersion: apps/v1
kind: Deployment
metadata:
  name: flask_app
spec:
  selector:
    matchLabels:
      run: flask_app
  replicas: 2
  template:
    metadata:
      labels:
        run: flask_app
    spec:
      containers:
      - name: flask_app
        image: gcr.io/ermias-biz/capstone-project-cluster-flask_app:latest
        ports:
        - containerPort: 80
        imagePullPolicy: Always