apiVersion: v1
kind: Service
metadata:
  name: flask-app
  labels:
    run: flask-app
spec:
  ports:
  - port: 8000
    name: http
    protocol: TCP
    targetPort: 8000
  selector:
    run: flask-app
  type: NodePort