apiVersion: apps/v1
kind: Deployment
metadata:
  name: nginx
spec:
  selector:
    matchLabels:
      run: nginx
  replicas: 2
  template:
    metadata:
      labels:
        run: nginx
    spec:
      volumes:
        - name: secret-volume
          secret:
            secretName: nginxsecret
      containers:
      - name: nginx
        image: gcr.io/ermias-biz/capstone-project-cluster-nginx:latest
        ports:
          - containerPort: 443
          - containerPort: 80
          volumeMounts:
            - mountPath: /etc/nginx/ssl
              name: secret-volume
#            - mountPath: /etc/nginx/conf.d
#              name: configmap-volume
        imagePullPolicy: Always